/* Generated by gen_journal.py — the single source of truth for Journal articles.
   Edit the generator, not this file. */
window.HD_JOURNAL = {
 "articles": [
  {
   "slug": "ultimate-guide-greek-honey",
   "url": "article-ultimate-guide-greek-honey.html",
   "title": "The Ultimate Guide to Greek Honey",
   "dek": "Everything worth knowing about Greek honey in one place — the varieties, the mountains, the harvest, the health substance behind the legend, and how to buy a jar that is actually real.",
   "category": [
    "guides"
   ],
   "catLabel": "Guides",
   "date": "2026-07-01",
   "readMin": 12,
   "image": "assets/products-images/thyme-origin.webp",
   "lang": "en",
   "featured": true,
   "pick": true,
   "most": true
  },
  {
   "slug": "greek-honey-vs-manuka",
   "url": "article-greek-honey-vs-manuka.html",
   "title": "Greek Honey vs Manuka Honey: An Honest Comparison",
   "dek": "Manuka built a global brand on one molecule and a grading system. Greek honey built three thousand years on flavour and place. Which one belongs in your kitchen — and what does the science really say?",
   "category": [
    "health",
    "guides"
   ],
   "catLabel": "Health",
   "date": "2026-06-30",
   "readMin": 8,
   "image": "assets/products-images/fir-vanilla-origin.webp",
   "lang": "en",
   "featured": false,
   "pick": true,
   "most": false
  },
  {
   "slug": "raw-honey-vs-processed-honey",
   "url": "article-raw-honey-vs-processed-honey.html",
   "title": "Raw Honey vs Processed Honey: What Is Actually Different?",
   "dek": "Heat, filtration and blending turn a living food into a shelf-stable syrup. A side-by-side account of what processing removes, what survives, and how to tell which jar you are holding.",
   "category": [
    "raw-honey",
    "health"
   ],
   "catLabel": "Raw Honey",
   "date": "2026-06-25",
   "readMin": 8,
   "image": "assets/products-images/acacia-serving.webp",
   "lang": "en",
   "featured": false,
   "pick": false,
   "most": true
  },
  {
   "slug": "raw-greek-honey",
   "url": "article-raw-greek-honey.html",
   "title": "Raw Greek Honey: What \"Raw\" Actually Means",
   "dek": "\"Raw\" is the most used and least protected word in the honey aisle. Here is what it technically means, how raw Greek honey is handled, and how to verify a jar yourself.",
   "category": [
    "raw-honey",
    "guides"
   ],
   "catLabel": "Raw Honey",
   "date": "2026-06-18",
   "readMin": 8,
   "image": "assets/products-images/acacia-origin.webp",
   "lang": "en",
   "featured": false,
   "pick": true,
   "most": false
  },
  {
   "slug": "greek-honey-health-benefits",
   "url": "article-greek-honey-health-benefits.html",
   "title": "Greek Honey & Health: What the Evidence Actually Says",
   "dek": "Antibacterial activity, antioxidants, coughs and colds, blood sugar — a sober, source-aware walk through what research supports, what it does not, and why rawness decides everything.",
   "category": [
    "health"
   ],
   "catLabel": "Health",
   "date": "2026-06-05",
   "readMin": 9,
   "image": "assets/products-images/fir-vanilla-serving.webp",
   "lang": "en",
   "featured": false,
   "pick": true,
   "most": true
  },
  {
   "slug": "taste-the-greek-sun",
   "url": "article-taste-the-greek-sun.html",
   "title": "Taste the Greek Sun: A Field Guide to Greek Honey",
   "dek": "What the Greek sun actually tastes like, why a single mountain matters, and how to read a jar in three movements.",
   "category": [
    "guides",
    "greek-nature"
   ],
   "catLabel": "Guides",
   "date": "2026-05-26",
   "readMin": 7,
   "image": "assets/olive-sunrise-poster.webp",
   "lang": "en",
   "featured": false,
   "pick": true,
   "most": false
  },
  {
   "slug": "how-greek-honey-is-made",
   "url": "article-how-greek-honey-is-made.html",
   "title": "From Hive to Jar: How Greek Honey Is Made",
   "dek": "Migratory hives, mountain summers, cold extraction and a village workshop — the actual production journey of a jar of Greek honey, season by season.",
   "category": [
    "beekeeping",
    "greek-nature"
   ],
   "catLabel": "Beekeeping",
   "date": "2026-05-20",
   "readMin": 8,
   "image": "assets/products-images/pine-origin.webp",
   "lang": "en",
   "featured": false,
   "pick": false,
   "most": true
  },
  {
   "slug": "greek-beekeeping-tradition",
   "url": "article-greek-beekeeping-tradition.html",
   "title": "Three Thousand Years of Greek Beekeeping",
   "dek": "From Aristotle’s hive observations to the mountain beekeepers of today — how Greece built, and kept, the oldest continuous beekeeping culture in Europe.",
   "category": [
    "beekeeping",
    "greek-nature"
   ],
   "catLabel": "Beekeeping",
   "date": "2026-05-02",
   "readMin": 7,
   "image": "assets/products-images/arbutus-origin.webp",
   "lang": "en",
   "featured": false,
   "pick": false,
   "most": false
  },
  {
   "slug": "greek-honey-varieties",
   "url": "article-greek-honey-varieties.html",
   "title": "Greek Honey Varieties Explained: Thyme, Pine, Fir, Chestnut & More",
   "dek": "Eight varieties define Greek beekeeping, and no two behave alike. Colour, aroma, texture, crystallization and what to eat each one with — a working reference.",
   "category": [
    "raw-honey",
    "guides"
   ],
   "catLabel": "Raw Honey",
   "date": "2026-04-30",
   "readMin": 9,
   "image": "assets/products-images/thyme-serving.webp",
   "lang": "en",
   "featured": false,
   "pick": true,
   "most": false
  },
  {
   "slug": "griekse-honing-smaak",
   "url": "article-griekse-honing-smaak.html",
   "title": "Waarom Griekse honing anders smaakt dan supermarkthoning",
   "dek": "Hoogte, wilde flora en koude slingering — waarom een pot Griekse berghoning niets deelt met de knijpfles uit het schap.",
   "category": [
    "raw-honey"
   ],
   "catLabel": "Raw Honey",
   "date": "2026-04-22",
   "readMin": 6,
   "image": "honeycomb.jpg",
   "lang": "nl",
   "featured": false,
   "pick": false,
   "most": true
  },
  {
   "slug": "why-does-honey-crystallize",
   "url": "article-why-does-honey-crystallize.html",
   "title": "Why Does Honey Crystallize? (And Why That Is Good News)",
   "dek": "Crystallized honey is not spoiled, old or fake — usually it is the opposite. The science of honey crystallization, which varieties set fastest, and how to re-liquefy a jar without ruining it.",
   "category": [
    "guides",
    "raw-honey"
   ],
   "catLabel": "Guides",
   "date": "2026-04-14",
   "readMin": 6,
   "image": "assets/products-images/orange-blossom-origin.webp",
   "lang": "en",
   "featured": false,
   "pick": false,
   "most": true
  },
  {
   "slug": "how-long-does-honey-last",
   "url": "article-how-long-does-honey-last.html",
   "title": "How Long Does Honey Last? Shelf Life, Storage & the 3,000-Year Jar",
   "dek": "Edible honey has been found in ancient tombs. Why honey effectively never spoils, what the date on the jar really means, and the few storage mistakes that can actually degrade it.",
   "category": [
    "guides"
   ],
   "catLabel": "Guides",
   "date": "2026-03-28",
   "readMin": 6,
   "image": "assets/products-images/chestnut-serving.webp",
   "lang": "en",
   "featured": false,
   "pick": false,
   "most": false
  },
  {
   "slug": "griekse-honing-nederland",
   "url": "article-griekse-honing-nederland.html",
   "title": "Waar koop je echte Griekse honing in Nederland?",
   "dek": "Van markt tot webshop: hoe je echte Griekse berghoning herkent tussen de \"Griekse stijl\"-blends.",
   "category": [
    "guides"
   ],
   "catLabel": "Guides",
   "date": "2026-03-15",
   "readMin": 6,
   "image": "assets/markt.webp",
   "lang": "nl",
   "featured": false,
   "pick": false,
   "most": false
  }
 ]
};
